### ISSUE TITLE
Failed to connect to `host=oracle-db user=postgres database=db`

### ISSUE THREAD

**Issue by holzeis** [p2pderivatives/p2pderivatives-oracle#37]
I tried to run the oracle as explained in the "Trying it out" section. Note, I had to change the permissions of the generated certs/db/db.key though. as described here https://stackoverflow.com/questions/55072221/deploying-postgresql-docker-with-ssl-certificate-and-key-with-volumes.

However, after running `docker-compose up` I run into the following error.

```
oracle-server_1  | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: dial error (dial tcp 172.28.0.2:5432: connect: connection timed out)Could not open database.","time":"2023-02-02T06:23:37Z"}
```

I've tried to adapt docker-compose.yml (see below) by adding more environment variables (as shown [here](https://github.com/p2pderivatives/p2pderivatives-oracle/blob/c34bd5b3aec2a4e547093133ee2c516b0e1a522f/deploy/docker-compose.yml) and added a default network.. but I did not got it working. Any suggestions?

```
version: '3.4'
services:
  oracle:
    build:
      context: .
    image: oracle-server
    command: |
      -config /config
      -appname p2pdoracle
      -e integration
      -migrate
    environment:
      - P2PDORACLE_DATABASE_HOST=db
      - P2PDORACLE_ORACLE_KEYFILE=/key/key.pem
      - P2PDORACLE_ORACLE_KEYPASS_FILE=/key/pass.txt
      - P2PDORACLE_DATABASE_DBPASSWORD=1234
      - P2PDORACLE_DATABASE_PORT=5432
      - P2PDORACLE_DATABASE_USER=postgres
      - P2PDORACLE_DATABASE_DBNAME=db
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./test/config:/config
      - ./certs/oracle:/key

  db:
    image: "postgres:12.2"
    command: |
      -c log_statement=all
      -c ssl=on
      -c ssl_cert_file=/certs/db.crt
      -c ssl_key_file=/certs/db.key
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    volumes:
      - oracle-db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./certs/db:/certs
volumes:
  oracle-db-data:
networks:
  default:
```

Full logs

```
Creating volume "p2pderivatives-oracle_oracle-db-data" with default driver
Creating p2pderivatives-oracle_oracle-db_1 ... done
Creating p2pderivatives-oracle_oracle-server_1 ... done
Attaching to p2pderivatives-oracle_oracle-db_1, p2pderivatives-oracle_oracle-server_1
oracle-server_1  | {"level":"info","msg":"ORM initialization starts","time":"2023-02-02T06:19:17Z"}
oracle-db_1      | The files belonging to this database system will be owned by user "postgres".
oracle-db_1      | This user must also own the server process.
oracle-db_1      | 
oracle-db_1      | The database cluster will be initialized with locale "en_US.utf8".
oracle-db_1      | The default database encoding has accordingly been set to "UTF8".
oracle-db_1      | The default text search configuration will be set to "english".
oracle-db_1      | 
oracle-db_1      | Data page checksums are disabled.
oracle-db_1      | 
oracle-db_1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
oracle-db_1      | creating subdirectories ... ok
oracle-db_1      | selecting dynamic shared memory implementation ... posix
oracle-db_1      | selecting default max_connections ... 100
oracle-db_1      | selecting default shared_buffers ... 128MB
oracle-db_1      | selecting default time zone ... Etc/UTC
oracle-db_1      | creating configuration files ... ok
oracle-db_1      | running bootstrap script ... ok
oracle-db_1      | performing post-bootstrap initialization ... ok
oracle-db_1      | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
oracle-db_1      | You can change this by editing pg_hba.conf or using the option -A, or
oracle-db_1      | --auth-local and --auth-host, the next time you run initdb.
oracle-db_1      | ok
oracle-db_1      | 
oracle-db_1      | 
oracle-db_1      | Success. You can now start the database server using:
oracle-db_1      | 
oracle-db_1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
oracle-db_1      | 
oracle-db_1      | waiting for server to start....2023-02-02 06:19:17.864 UTC [46] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
oracle-db_1      | 2023-02-02 06:19:17.886 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
oracle-db_1      | 2023-02-02 06:19:18.005 UTC [47] LOG:  database system was shut down at 2023-02-02 06:19:14 UTC
oracle-db_1      | 2023-02-02 06:19:18.041 UTC [46] LOG:  database system is ready to accept connections
oracle-db_1      |  done
oracle-db_1      | server started
oracle-db_1      | 2023-02-02 06:19:18.560 UTC [62] LOG:  statement: CREATE DATABASE "db" ;
oracle-db_1      | CREATE DATABASE
oracle-db_1      | 
oracle-db_1      | 
oracle-db_1      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
oracle-db_1      | 
oracle-db_1      | 2023-02-02 06:19:19.741 UTC [46] LOG:  received fast shutdown request
oracle-db_1      | waiting for server to shut down....2023-02-02 06:19:19.774 UTC [46] LOG:  aborting any active transactions
oracle-db_1      | 2023-02-02 06:19:19.777 UTC [46] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
oracle-db_1      | 2023-02-02 06:19:19.779 UTC [48] LOG:  shutting down
oracle-db_1      | 2023-02-02 06:19:20.001 UTC [46] LOG:  database system is shut down
oracle-db_1      |  done
oracle-db_1      | server stopped
oracle-db_1      | 
oracle-db_1      | PostgreSQL init process complete; ready for start up.
oracle-db_1      | 
oracle-db_1      | 2023-02-02 06:19:20.089 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
oracle-db_1      | 2023-02-02 06:19:20.089 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
oracle-db_1      | 2023-02-02 06:19:20.089 UTC [1] LOG:  listening on IPv6 address "::", port 5432
oracle-db_1      | 2023-02-02 06:19:20.136 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
oracle-db_1      | 2023-02-02 06:19:20.230 UTC [64] LOG:  database system was shut down at 2023-02-02 06:19:19 UTC
oracle-db_1      | 2023-02-02 06:19:20.267 UTC [1] LOG:  database system is ready to accept connections
oracle-server_1  | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: dial error (dial tcp 172.28.0.2:5432: connect: connection timed out)Could not open database.","time":"2023-02-02T06:23:37Z"}
oracle-server_1  | {"level":"info","msg":"ORM initialization end","time":"2023-02-02T06:23:37Z"}
oracle-server_1  | panic: Could not initialize database.
oracle-server_1  | 
oracle-server_1  | goroutine 1 [running]:
oracle-server_1  | main.newInitializedOrm(0xc0003fc500, 0xc0004465e0, 0xc0000b6f48)
oracle-server_1  | 	/p2pderivatives-oracle/cmd/p2pdoracle/main.go:143 +0x1b8
oracle-server_1  | main.NewDefaultOracleAPI(0xc0004465e0, 0xc0003fc500, 0x0, 0x0)
oracle-server_1  | 	/p2pderivatives-oracle/cmd/p2pdoracle/main.go:183 +0x19b
oracle-server_1  | main.newInitializedRouter(0xc0004465e0, 0xc0003fc500, 0x0)
oracle-server_1  | 	/p2pderivatives-oracle/cmd/p2pdoracle/main.go:157 +0x39
oracle-server_1  | main.main()
oracle-server_1  | 	/p2pderivatives-oracle/cmd/p2pdoracle/main.go:70 +0x189
```
